#!/usr/bin/env node
/**
 * Emits `.d.ts` type declarations for the public API surface (ADR-0017), generated by the
 * TypeScript compiler directly from the JSDoc already present in `src/` — no source file is
 * converted to `.ts` and `typescript` is never imported at runtime (constitution's build-free
 * boundary). Output lands in `types/`, mirroring `package.json`'s `exports` map.
 *
 * `tsc` runs with `checkJs: true` for the best declaration quality, but a handful of internal,
 * non-public-API lines in the existing JSDoc are looser than TypeScript would like (see
 * `adr/0017-generated-type-declarations.md` and the TASK-002 handoff for the specific list).
 * Those are pre-existing type-checking diagnostics, not declaration-emission failures — `tsc`
 * still emits accurate `.d.ts` files for every module despite them (`noEmitOnError: false`), so
 * this script treats a non-zero `tsc` exit as advisory and instead verifies the artifacts that
 * actually matter: the required output files exist and contain the expected exported symbols.
 *
 * Usage: npm run build:types
 */
import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const tscBin = path.join(root, 'node_modules', '.bin', process.platform === 'win32' ? 'tsc.cmd' : 'tsc');

/** Files and the exported symbols each one must contain, once generation succeeds. */
const REQUIRED = [
  {
    file: 'types/core/core.d.ts',
    symbols: ['BaseComponent', 'html', 'define', 'createReactive', 'createStore', 'morph', 'safeUrl', 'HtmlString', 'unsafe', 'escapeHtml'],
  },
  { file: 'types/core/authoring.d.ts', symbols: ['component'] },
  { file: 'types/core/app.d.ts', symbols: ['createAsyncState', 'fetchJson', 'HttpError', 'createForm', 'createHashRouter'] },
  { file: 'types/core/base-component.d.ts', symbols: ['BaseComponent'] },
];

console.log('[build:types] running tsc (declaration emit only)…');
const result = spawnSync(tscBin, ['-p', path.join(root, 'tsconfig.json')], {
  cwd: root,
  encoding: 'utf8',
});

if (result.stdout?.trim()) console.log(result.stdout.trim());
if (result.stderr?.trim()) console.error(result.stderr.trim());

if (result.error) {
  console.error(`[build:types] failed to spawn tsc: ${result.error.message}`);
  process.exit(1);
}

const diagnosticCount = (result.stdout ?? '').split('\n').filter((line) => /error TS\d+/.test(line)).length;
if (diagnosticCount > 0) {
  console.warn(
    `[build:types] ${diagnosticCount} pre-existing checkJs diagnostic(s) in implementation-internal ` +
    `code (not the public API surface) — tracked as known gaps in adr/0017-generated-type-declarations.md. ` +
    `Declaration emission still proceeded (noEmitOnError: false); verifying output below.`,
  );
}

let failed = false;
for (const { file, symbols } of REQUIRED) {
  const fullPath = path.join(root, file);
  if (!existsSync(fullPath)) {
    console.error(`[build:types] MISSING required declaration file: ${file}`);
    failed = true;
    continue;
  }
  const content = readFileSync(fullPath, 'utf8');
  for (const symbol of symbols) {
    if (!content.includes(symbol)) {
      console.error(`[build:types] ${file} is missing expected symbol "${symbol}"`);
      failed = true;
    }
  }
}

if (failed) {
  console.error('[build:types] TYPE DECLARATION GATE FAILED');
  process.exit(1);
}

console.log(`[build:types] OK — ${REQUIRED.length} required declaration file(s) verified.`);
